[crates.anyhow]
version = "1.0.102"

[crates.dirs]
version = "6.0.0"

[crates.flate2]
version = "1.1.9"

[crates.regex]
version = "1.12.3"

[crates.roxmltree]
version = "0.21.1"

[crates.tar]
version = "0.4.44"

[crates.thiserror]
version = "2.0.18"

[crates.ureq]
version = "3.2.0"

[crates.serde]
version = "1.0.228"

[crates.serde_json]
version = "1.0.149"

[crates.bevy]
version = "0.18.1"
